{% set build = 0 %}
{% set version = '1.8.5' %}

package:
    name: openmpi
    version: {{version}}

about:
    home: http://www.open-mpi.org/
    license: New BSD (http://www.open-mpi.org/community/license.php)
    summary: 'Open MPI: A high performance message passing library.'

source:
    fn: openmpi-1.8.5.tar.gz
    url: http://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-1.8.5.tar.gz
    md5: 9c0878763c750dcb17f52701e26dc0f5

requirements:
    conflicts:
        - mpich
        - mpich2

build:
    number: {{build}}
    string: cuda_{{build}}
