{% set build = 1 %}
{% set version = '1.10.0' %}

package:
    name: openmpi
    version: {{version}}

about:
    home: http://www.open-mpi.org/
    license: New BSD (http://www.open-mpi.org/community/license.php)
    summary: 'Open MPI: A high performance message passing library.'

source:
    fn: openmpi-{{version}}.tar.bz2
    url: http://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-{{version}}.tar.bz2
    md5: 280cf952de68369cebaca886c5ce0304

requirements:
    conflicts:
        - mpich
        - mpich2

build:
    number: {{build}}
    string: cuda_{{build}}
