{% set build = 0 %}
{% set version = '1.8.8' %}

package:
    name: openmpi
    version: {{version}}

about:
    home: http://www.open-mpi.org/
    license: New BSD (http://www.open-mpi.org/community/license.php)
    summary: 'Open MPI: A high performance message passing library.'

source:
    fn: openmpi-{{version}}.tar.gz
    url: http://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-{{version}}.tar.gz
    md5: 88f2f6bf4a95df63a95d31cf31c20ebb

requirements:
    conflicts:
        - mpich
        - mpich2

build:
    number: {{build}}
    string: cuda_{{build}}
