{% set build = 0 %}

package:
    name: openmpi
    version: !!str 1.8.5rc3

about:
    home: http://www.open-mpi.org/
    license: New BSD (http://www.open-mpi.org/community/license.php)
    summary: 'Open MPI: A high performance message passing library.'

source:
    fn: openmpi-1.8.5rc3.tar.gz
    url: http://www.open-mpi.org/software/ompi/v1.8/downloads/openmpi-1.8.5rc3.tar.gz
    md5: 2dfb5bf82eafb91b8d04e054dc5ef5d6

requirements:
    conflicts:
        - mpich
        - mpich2

build:
    number: {{build}}
    string: ubuntu1404_cuda65_{{build}}
