{% set build = 0 %}
{% set version = '1.10.2' %}

package:
    name: openmpi
    version: {{version}}

about:
    home: http://www.open-mpi.org/
    license: New BSD (http://www.open-mpi.org/community/license.php)
    summary: 'Open MPI: A high performance message passing library.'

source:
    fn: openmpi-{{version}}.tar.bz2
    url: http://www.open-mpi.org/software/ompi/v1.10/downloads/openmpi-{{version}}.tar.bz2
    md5: b2f43d9635d2d52826e5ef9feb97fd4c

requirements:
    conflicts:
        - mpich
        - mpich2

build:
    number: {{build}}
    string: cuda_{{build}}
